-- Create asset_classification table
CREATE TABLE IF NOT EXISTS asset_classification (
    ac_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    classification_type TEXT NOT NULL,
    asset_category TEXT
);

-- Seed classification types
INSERT INTO asset_classification (classification_type, asset_category) VALUES
    ('Household Asset', 'Asset'),
    ('Primary residence', 'Real Estate'),
    ('Vacation home', 'Real Estate'),
    ('Rental property', 'Real Estate'),
    ('Undeveloped land/lot', 'Real Estate'),
    ('Condominium', 'Real Estate'),
    ('Timeshare', 'Real Estate'),
    ('Home equity/ownership interest', 'Liability'),
    ('Household furnishings', 'Asset'),
    ('Living room furniture', 'Asset'),
    ('Bedroom furniture', 'Asset'),
    ('Dining room furniture', 'Asset'),
    ('Home office furniture', 'Asset'),
    ('Major appliances (refrigerator/oven/washer/dryer)', 'Asset'),
    ('Small kitchen appliances', 'Asset'),
    ('Electronics (TVs/computers/tablets)', 'Asset'),
    ('Home theater/audio equipment', 'Asset'),
    ('Phones and accessories', 'Asset'),
    ('Cameras and photo equipment', 'Asset'),
    ('Jewelry', 'Asset'),
    ('Watches', 'Asset'),
    ('Handbags/accessories (high-value)', 'Asset'),
    ('Artwork', 'Asset'),
    ('Antiques/collectibles', 'Asset'),
    ('Precious metals (gold/silver/coins)', 'Asset'),
    ('Firearms', 'Asset'),
    ('Tools and equipment', 'Asset'),
    ('Lawn/garden equipment', 'Asset'),
    ('Power tools', 'Asset'),
    ('Outdoor furniture', 'Asset'),
    ('Grill/smoker', 'Asset'),
    ('Sporting goods', 'Asset'),
    ('Musical instruments', 'Asset'),
    ('Hobby collections (stamps/cards/models)', 'Asset'),
    ('Books and libraries', 'Asset'),
    ('Vehicles (cars/trucks/SUVs)', 'Vehicle'),
    ('Motorcycle', 'Vehicle'),
    ('Boat/watercraft', 'Vehicle'),
    ('Trailer', 'Vehicle'),
    ('RV/camper', 'Vehicle'),
    ('Golf cart/ATV/UTV', 'Vehicle'),
    ('Bicycles/e-bikes', 'Vehicle'),
    ('Vehicle titles/registrations', 'Vehicle'),
    ('Cash on hand', 'Cash'),
    ('Checking account', 'Cash'),
    ('Savings account', 'Cash'),
    ('Money market account', 'Cash'),
    ('Certificates of deposit (CDs)', 'Cash'),
    ('Brokerage account (taxable)', 'Cash'),
    ('Stocks', 'Investment'),
    ('Bonds', 'Asset'),
    ('Mutual funds', 'Asset'),
    ('ETFs', 'Asset'),
    ('Treasury securities', 'Asset'),
    ('I Bonds', 'Asset'),
    ('Retirement accounts (401(k)/403(b)/457)', 'Asset'),
    ('Traditional IRA', 'Asset'),
    ('Roth IRA', 'Asset'),
    ('Pension benefits', 'Asset'),
    ('Annuities', 'Asset'),
    ('Life insurance policy (cash value/benefit)', 'Insurance'),
    ('Health savings account (HSA)', 'Investment'),
    ('529 college savings plan', 'Investment'),
    ('Business ownership interest (LLC/S-corp/partnership)', 'Investment'),
    ('Sole proprietorship assets', 'Asset'),
    ('Business equipment', 'Asset'),
    ('Business bank account', 'Cash'),
    ('Intellectual property rights (royalties/patents)', 'Asset'),
    ('Safe deposit box contents', 'Asset'),
    ('Digital assets (online accounts/crypto)', 'Asset'),
    ('Cryptocurrency holdings', 'Asset'),
    ('Domain names/websites', 'Asset'),
    ('Prepaid funeral/burial plan', 'Asset'),
    ('Cemetery plot/columbarium niche', 'Asset'),
    ('Storage unit contents', 'Asset'),
    ('Security deposits (refundable)', 'Cash'),
    ('Refunds/credits owed', 'Cash'),
    ('Promissory notes/loans receivable', 'Asset');
